name: 'Terraform'
on:
  workflow_dispatch: null
  push:                                 
    branches:                                 
    - main                            
  pull_request:
                                                       
env:                                   
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:                               
  terraform:                                 
    name: 'Terraform'                                 
    runs-on: ubuntu-latest                             
    steps:                             
        # Checkout the repository to the GitHub Actions runner        
        - name: Checkout                                   
          uses: actions/checkout@v3
    # Runs a single command using the runners shell     
        - name: 'Terraform init' 
          id: init                                   
          run: |
            terraform init                           

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1
        
        - name: 'Terraform plan'                                   
          id: plan                                   
          run: |
            terraform plan                 
                                        
        - name: 'Terraform apply' 
          id: apply            
          run: | 
            terraform apply -auto-approve
